import { graphql } from 'gatsby';
import React from 'react';
import Layout from '../components/layout';
import styled from '@emotion/styled';

const CardSubtitle = styled.p`
  color: grey;
  font-size: 12px;
`;

const GithubCardWrapper = styled.div`
  text-align: center;
`;

interface PostProps {
  data: {
    markdownRemark: {
      frontmatter: {
        title: string;
        excerpt: string;
        githubUrl: string;
      };
      html: string;
    };
  };
  pageContext: {
    slug: string;
    primaryTag: string;
  };
}

const PageTemplate: React.FC<PostProps> = props => {
  const post = props.data.markdownRemark;
  const repoSlug = props.data.markdownRemark.frontmatter.githubUrl.replace('https://github.com/', '');
  return (
    <Layout>
      <h1>{props.data.markdownRemark.frontmatter.title}</h1>
      <h4>{props.data.markdownRemark.frontmatter.excerpt}</h4>
      <GithubCardWrapper>
        <a href={props.data.markdownRemark.frontmatter.githubUrl}><img src={`https://gh-card.dev/repos/${repoSlug}.svg`} alt="Github Card"/></a>
        <CardSubtitle>Card generated by <a href="https://gh-card.dev/">gh-card.dev</a></CardSubtitle>
      </GithubCardWrapper>
      <div
        dangerouslySetInnerHTML={{ __html: post.html }}
      />
    </Layout>
  );
};

export const query = graphql`
  query($slug: String) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
    frontmatter {
      title
      excerpt
      githubUrl
    }
      html
    }
  }
`;

export default PageTemplate;
