import { graphql } from 'gatsby';
import React from 'react';
import Layout from '../components/layout';
import styled from '@emotion/styled';
import { Image } from '../interfaces';
import GatsbyImage from 'gatsby-image';
import colors from '../styles/colors';

const CardSubtitle = styled.p`
  color: grey;
  font-size: 12px;
`;

const GithubCardWrapper = styled.div`
  text-align: center;
`;

const LiveProjectLink = styled.a`
   font-weight: 600;
    text-decoration: none;
    color: currentColor;
    transition: all 150ms ease-in-out;
    margin-top: 2rem;

    span {
        margin-left: 1em;
        transform: translateX(-8px);
        display: inline-block;
        transition: transform 400ms ease-in-out;
    }

    &:hover {
                color: ${colors.blue500};
            transition: all 150ms ease-in-out;

            span {
                transform: translateX(0px);
                opacity: 1;
                transition: transform 150ms ease-in-out;
            }
    }
`;

interface PostProps {
  data: {
    markdownRemark: {
      frontmatter: {
        title: string;
        excerpt: string;
        githubUrl: string;
        image: Image;
        liveProject: string;
      };
      html: string;
    };
  };
  pageContext: {
    slug: string;
    primaryTag: string;
  };
}

const PageTemplate: React.FC<PostProps> = props => {
  const post = props.data.markdownRemark;
  const repoSlug = props.data.markdownRemark.frontmatter.githubUrl.replace('https://github.com/', '');
  return (
    <Layout>
      <h1>{props.data.markdownRemark.frontmatter.title}</h1>
      <h4>{props.data.markdownRemark.frontmatter.excerpt}</h4>
      <GithubCardWrapper>
        <a href={props.data.markdownRemark.frontmatter.githubUrl}><img src={`https://gh-card.dev/repos/${repoSlug}.svg`} alt="Github Card"/></a>
        <CardSubtitle>Card generated by <a href="https://gh-card.dev/">gh-card.dev</a></CardSubtitle>
      </GithubCardWrapper>
      <GatsbyImage fluid={props.data.markdownRemark.frontmatter.image.childImageSharp.fluid} />
      <div style={{ textAlign: 'center', marginTop: '2rem' }}>
        {
          props.data.markdownRemark.frontmatter.liveProject ?
            <LiveProjectLink href={props.data.markdownRemark.frontmatter.liveProject}>See live project <span>&#8594;</span></LiveProjectLink> : null
        }
      </div>
      <div
        dangerouslySetInnerHTML={{ __html: post.html }}
      />
    </Layout>
  );
};

export const query = graphql`
  query($slug: String) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
    frontmatter {
      title
      excerpt
      githubUrl
      liveProject
      image {
        childImageSharp {
          fluid(maxWidth: 3720) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
      html
    }
  }
`;

export default PageTemplate;
