import { graphql } from 'gatsby';
import React from 'react';
import Layout from '../components/layout';
import styled from '@emotion/styled';
import GatsbyImage from 'gatsby-image';
import colors from '../styles/colors';
import { Helmet } from 'react-helmet';
import config from '../website-config';
import { Image } from '../interfaces';

const CardSubtitle = styled.p`
  color: grey;
  font-size: 12px;
`;

const GithubCardWrapper = styled.div`
  text-align: center;
`;

const LiveProjectLink = styled.a`
   font-weight: 600;
    text-decoration: none;
    color: currentColor;
    transition: all 150ms ease-in-out;
    margin-top: 2rem;

    span {
        margin-left: 1em;
        transform: translateX(-8px);
        display: inline-block;
        transition: transform 400ms ease-in-out;
    }

    &:hover {
                color: ${colors.blue500};
            transition: all 150ms ease-in-out;

            span {
                transform: translateX(0px);
                opacity: 1;
                transition: transform 150ms ease-in-out;
            }
    }
`;

interface PostProps {
  data: {
    markdownRemark: {
      frontmatter: {
        title: string;
        excerpt: string;
        githubUrl: string;
        image: Image;
        liveProject: string;
      };
      html: string;
    };
  };
  path: string;
  pageContext: {
    slug: string;
    primaryTag: string;
  };
}

const PageTemplate: React.FC<PostProps> = props => {
  const post = props.data.markdownRemark;
  const repoSlug = props.data.markdownRemark.frontmatter.githubUrl.replace('https://github.com/', '');
  const { title } = props.data.markdownRemark.frontmatter;
  const description = props.data.markdownRemark.frontmatter.excerpt;
  const pageUrl = `${config.siteUrl}/${props.path}`;
  return (
    <>
      <Helmet>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta property="og:site_name" content={config.title} />
        <meta property="og:type" content="website" />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta property="og:url" content={pageUrl} />
        <meta
          property="og:image"
          content={`${config.siteUrl}${props.data.markdownRemark.frontmatter.image.childImageSharp.fixed.src}`}
        />
        {config.facebook && (
          <meta property="article:publisher" content={config.facebook} />
        )}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={description} />
        <meta name="twitter:url" content={pageUrl} />
        <meta
          name="twitter:image"
          content={`${config.siteUrl}${props.data.markdownRemark.frontmatter.image.childImageSharp.fixed.src}`}
        />
        {config.twitter && (
          <meta
            name="twitter:site"
            content={`@${config.twitter.split('https://twitter.com/')[1]}`}
          />
        )}
      </Helmet>
      <Layout>
        <h1>{props.data.markdownRemark.frontmatter.title}</h1>
        <h4>{props.data.markdownRemark.frontmatter.excerpt}</h4>
        <GithubCardWrapper>
          <a href={props.data.markdownRemark.frontmatter.githubUrl}><img src={`https://gh-card.dev/repos/${repoSlug}.svg`} alt="Github Card"/></a>
          <CardSubtitle>Card generated by <a href="https://gh-card.dev/">gh-card.dev</a></CardSubtitle>
        </GithubCardWrapper>
        <GatsbyImage fluid={props.data.markdownRemark.frontmatter.image.childImageSharp.fluid} />
        <div style={{ textAlign: 'center', marginTop: '2rem' }}>
          {
            props.data.markdownRemark.frontmatter.liveProject ?
              <LiveProjectLink href={props.data.markdownRemark.frontmatter.liveProject}>See live project <span>&#8594;</span></LiveProjectLink> : null
          }
        </div>
        <div
          dangerouslySetInnerHTML={{ __html: post.html }}
        />
      </Layout>
    </>
  );
};

export const query = graphql`
  query($slug: String) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
    frontmatter {
      title
      excerpt
      githubUrl
      liveProject
      image {
        childImageSharp {
          fluid(maxWidth: 3720) {
            ...GatsbyImageSharpFluid
          }
          fixed {
            src
          }
        }
      }
    }
      html
    }
  }
`;

export default PageTemplate;
